name: Pack Contoso_University_Core

on:
  push:
    paths:
      - contents/**
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/contoso_university_core.zip
          solution-folder: contents
          solution-type: Both
      - uses: actions/upload-artifac@v2
        with:
          name: packed-solution
          path: out/

    